In [1]:
!pip install -q kaggle
from google.colab import files
uploaded = files.upload()

Saving kaggle.json to kaggle (1).json


In [2]:
!mkdir ../root/.kaggle
!cp ../content/kaggle.json ../root/.kaggle


mkdir: cannot create directory ‘../root/.kaggle’: File exists


In [3]:
!ls ../root/.kaggle

kaggle.json


In [4]:
!kaggle datasets download -d grassknoted/asl-alphabet --force

 56% 588M/1.03G [00:04<00:03, 136MB/s]
User cancelled operation


In [5]:
!unzip asl-alphabet.zip

Archive:  asl-alphabet.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of asl-alphabet.zip or
        asl-alphabet.zip.zip, and cannot find asl-alphabet.zip.ZIP, period.


In [1]:
#[A-Z, del, nothing, space]
import keras
!pip install numpy 
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import os

num_category = 29
all_data = []
%cd asl_alphabet_train/asl_alphabet_train/A
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Using TensorFlow backend.


/content/asl_alphabet_train/asl_alphabet_train/A


In [2]:
%cd ../B 
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/B


In [3]:
%cd ../C
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
print(len(all_data))

/content/asl_alphabet_train/asl_alphabet_train/C
9000


In [5]:
%cd ../D
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
print(len(all_data))

/content/asl_alphabet_train/asl_alphabet_train/D
12000
/content/asl_alphabet_train/asl_alphabet_train/D
15000


In [6]:
%cd ../E
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/E


In [7]:
%cd ../F
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/F


In [8]:
%cd ../G
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/G


In [9]:
%cd ../H
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/H


In [10]:
%cd ../I
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/I


In [11]:
%cd ../J
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/J


In [12]:
%cd ../K
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/K


In [13]:
%cd ../L
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/L


In [14]:
%cd ../M
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/M


In [15]:
%cd ../N
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/N


In [16]:
%cd ../O
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/O


In [17]:
%cd ../P
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/P


In [18]:
%cd ../Q
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/Q


In [19]:
%cd ../R
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/R


In [20]:
%cd ../S 
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/S


In [21]:
%cd ../T 
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/T


In [22]:
%cd ../U
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/U


In [23]:
%cd ../V 
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/V


In [24]:
%cd ../W
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/W


In [25]:
%cd ../X
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/X


In [26]:
%cd ../Y 
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/Y


In [27]:
%cd ../Z
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/Z


In [28]:
%cd ../'del'
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

/content/asl_alphabet_train/asl_alphabet_train/del


In [29]:
%cd ../nothing
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

/content/asl_alphabet_train/asl_alphabet_train/nothing


In [30]:
%cd ../space
for filename in os.listdir("."):
  im = cv2.imread(filename)
  grey = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  all_data.append([grey, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

/content/asl_alphabet_train/asl_alphabet_train/space


In [31]:
import random
import numpy as np
print(len(all_data))
shuffled_data = list(all_data)
random.shuffle(shuffled_data)
smaller_data = shuffled_data[:2000]
X_train = []
y_train = []
for i in smaller_data:
  X_train.append(i[0])
  y_train.append(i[1])


X_train_4D = []
for i in X_train:
  a = []
  for j in i:
    b = []
    for k in j:
      c = []
      c.append(k)
      b.append(c)
    a.append(b)
  X_train_4D.append(a)

X_babyfood = np.array(X_train_4D)
print(X_babyfood.shape)
y_babyfood = np.array(y_train)
print(y_babyfood)


90000
(2000, 200, 200, 1)
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [32]:
import keras
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 29
epochs = 20
input_shape = (200, 200, 1)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])


model.fit(X_babyfood, y_babyfood,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/20





2000/2000 [==============================] - 21s 11ms/step - loss: 15.5534 - acc: 0.0330
Epoch 2/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.6184 - acc: 0.0310
Epoch 3/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.5378 - acc: 0.0360
Epoch 4/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.5701 - acc: 0.0340
Epoch 5/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.6178 - acc: 0.0310
Epoch 6/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.5540 - acc: 0.0350
Epoch 7/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.5459 - acc: 0.0355
Epoch 8/20
2000/2000 [==============================] - 3s 2ms/step - loss: 15.5943 - ac